services:
  db:
    image: postgres:16
    container_name: investify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investify_db
    ports:
      - "5432:5432"
    volumes:
      - investify-db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: investify-backend
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  investify-db-data: