services:
  db:
    image: postgres:16
    container_name: investify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investify_db
    volumes:
      - investify-db-data:/var/lib/postgresql/data
    networks:
      - investify-network

  backend:
    build: .
    container_name: investify-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - investify-network

volumes:
  investify-db-data:

networks:
  investify-network: