spring:
  application:
    name: backend
  config:
    import: optional:classpath:application-APIs.properties
  codec:
    max-in-memory-size: 1000MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aws:
    access-key: ${aws.access-key}
    secret-key: ${aws.secret-key}
    s3:
      bucket-name: ${s3.bucket-name}
      region: ${s3.region}
  datasource:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${investify.email}
    password: ${investify.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  api:
    key:
      alphaVantage: ${alphaVantage.api.key}
      coinMarket: ${coinMarket.api.key}
      openAI: ${azure.openAI.api.key}
      polygon: ${polygon.api.key}
      twelveData: ${twelveData.api.keys}
    demokey:
      twelveData: ${twelveData.api.demokey}
  frontend:
    url: ${frontend.url}